# Generated by Django 4.1.6 on 2023-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('actores', models.TextField()),
                ('clasificacion', models.CharField(max_length=10)),
                ('duracion', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='peliculas/')),
            ],
        ),
    ]
