# Generated by Django 4.1.6 on 2023-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
