# Generated by Django 4.1.6 on 2023-03-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
